openapi: 3.0.0
info:
    title: Product API
    version: 1.0.0
servers:
    - url: https://api.example.com/v1
paths:
    /products:
        get:
            summary: Get all products
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Product'
        post:
            summary: Create a new product
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Product'
            responses:
                '201':
                    description: Product created successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Product'
    /products/{id}:
        get:
            summary: Get a product by ID
            parameters:
                - name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Product'
        put:
            summary: Update a product by ID
            parameters:
                - name: id
                    in: path
                    required: true
                    schema:
                        type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Product'
            responses:
                '200':
                    description: Product updated successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Product'
        delete:
            summary: Delete a product by ID
            parameters:
                - name: id
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                '204':
                    description: Product deleted successfully
components:
    schemas:
        Product:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                price:
                    type: number