name: 'APIOps - From Validation to Portal / Marketplace'
on:
  workflow_call:
    inputs:
      spec-file:
        required: true
        type: string
      api-product-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ inputs.spec-file }} 

    - name: Rename the API Definition
      run: mv ${{ inputs.spec-file }} ${{ inputs.api-product-name }}-unbundled.yaml

    - name: redocly bundle
      run: npx @redocly/cli bundle ${{ inputs.api-product-name }}-unbundled.yaml --output ./${{ inputs.api-product-name }}.yaml
      
    - name: Run Vacuum CLI for linting
      run: npx @quobix/vacuum lint ${{ inputs.api-product-name }}.yaml -d
   
    - name: Archive bundled API Definition
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.api-product-name }}
        path: ${{ inputs.api-product-name }}.yaml
    
  deploy_to_dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: deploy-api-definition.sh
      - name: Download the bundled API Definition
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.api-product-name }}

      - name: Deploy API Definition
        run: sh ./deploy-api-definition.sh


  contract_test_in_dev:
    needs: deploy_to_dev
    runs-on: ubuntu-latest
    steps:
      - name: Download the bundled API Definition
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.api-product-name }}
      - name: Run Portman tests
        run: npx @apideck/portman --local ${{ inputs.api-product-name }}.yaml --runNewman --output ${{ inputs.api-product-name }}.postman_collection.json
      - name: Upload Postman collection
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.api-product-name }}-postman-collection
          path: ${{ inputs.api-product-name }}.postman_collection.json
 
  deploy-to-prod:
    needs: contract_test_in_dev
    runs-on: ubuntu-latest
    steps:
    - name: Download the bundled API Definition
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.api-product-name }}
    - name: Deploy to API Portal/Marketplace
      run: |
        # The command to deploy the API to the Portal or Marketplace
        # will depend on the specific platform being used