name: APIOps for Petstore API

on:
    push:
        branches:
        - main

jobs:
    call-apiops-local-repo:
        uses: ./.github/workflows/apiops-ci-cd-pam.yml
        with:
            spec-file: './openapi.yaml'
            api-product-name: 'openapi'